import pytest
from unittest.mock import patch, MagicMock
from app.core.use_cases.game_service import GameService
from app.core.domain.location import Location, Coordinates
from app.core.domain.player import Player

# Mock Repository
class MockRepository:
    def __init__(self):
        self.locations = {}
        self.players = {}

    def get_player(self, player_id: str):
        return self.players.get(player_id)

    def save_player(self, player: Player):
        self.players[player.id] = player
        return player

    def get_location(self, location_id: str):
        return self.locations.get(location_id)

    def create_location(self, location: Location):
        self.locations[location.id] = location
        return location

    def get_location_by_coordinates(self, x: int, y: int, z: int):
        for loc in self.locations.values():
            if loc.coordinates and loc.coordinates.x == x and loc.coordinates.y == y and loc.coordinates.z == z:
                return loc
        return None

    def get_world_time(self):
        from app.core.domain.time_system import WorldTime
        return WorldTime()
        
    def save_world_time(self, t):
        pass

    def get_player_by_name(self, name):
        return None

def test_ensure_neighbors_on_start():
    repo = MockRepository()
    service = GameService(repo)
    
    # Create player (should generate start + neighbors)
    player, _ = service.create_new_player("Explorer")
    
    # Start usually at 0,0,0
    start_loc = repo.get_location_by_coordinates(0, 0, 0)
    assert start_loc is not None
    
    # Check neighbors (North 0,1, South 0,-1, East 1,0, West -1,0)
    # These might be generated by the initial 5x5 chunk if it covers them.
    # But _ensure_neighbors guarantees it.
    assert repo.get_location_by_coordinates(0, 1, 0) is not None
    assert repo.get_location_by_coordinates(0, -1, 0) is not None
    assert repo.get_location_by_coordinates(1, 0, 0) is not None
    assert repo.get_location_by_coordinates(-1, 0, 0) is not None
    
    # Check bidirectional links
    assert "north" in start_loc.exits
    north_loc = repo.get_location(start_loc.exits["north"])
    assert north_loc.exits["south"] == start_loc.id

def test_infinite_expansion_on_move():
    repo = MockRepository()
    service = GameService(repo)
    
    # Setup: 0,0 and 0,1 exist. 0,2 does NOT exist.
    loc_0_0 = Location(id="loc_0_0_0", name="Start", description="Start", coordinates=Coordinates(x=0,y=0,z=0))
    loc_0_1 = Location(id="loc_0_1_0", name="North", description="North", coordinates=Coordinates(x=0,y=1,z=0))
    
    # Link them
    loc_0_0.exits["north"] = loc_0_1.id
    loc_0_1.exits["south"] = loc_0_0.id
    
    repo.create_location(loc_0_0)
    repo.create_location(loc_0_1)
    
    player = Player(id="p1", name="Hero", current_location_id="loc_0_0_0")
    repo.save_player(player)
    
    # Move North to 0,1
    # This should trigger _ensure_neighbors for 0,1
    # 0,1's North neighbor is 0,2. It should be generated.
    
    msg, p, final_loc = service.process_command(player.id, "north")
    
    assert final_loc.id == "loc_0_1_0"
    
    # Check if 0,2 was generated
    loc_0_2 = repo.get_location_by_coordinates(0, 2, 0)
    assert loc_0_2 is not None
    # Can be Forest OR a water source (Lake, River, Stream, Well)
    valid_names = ["Forest", "River", "Stream", "Lake", "Well"]
    assert any(name in loc_0_2.name for name in valid_names)
    
    # Check link
    assert "north" in final_loc.exits
    assert final_loc.exits["north"] == loc_0_2.id
    assert loc_0_2.exits["south"] == final_loc.id
